"""Figures and numbers for the controller pulse/velocity report.

    python3 reports/controller_pulse/make_figs.py

Reads the Genesis sweeps in reports/data/ and the profile code of
franka_controllers/scripts/linear_vel_test.py; writes figs/*.pdf and numbers.tex.
"""

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT / "reports" / "tools"))

from figstyle import BLUE, C, DIVERGING, GRID, INK, INK2, MUTED, SHADE, TEXTWIDTH, label_end, save, setup  # noqa: E402
from slip_model import (  # noqa: E402
    controller_chain,
    g_components,
    second_order_lowpass,
    simulate_slip,
    slip_closed,
    slip_star,
    timing_sensitivity,
    trapezoid,
    v_star,
    w_end,
)

import matplotlib.pyplot as plt  # noqa: E402

FIGS = HERE / "figs"
FIGS.mkdir(exist_ok=True)
DATA = ROOT / "reports" / "data"
CTRL = ROOT / "franka_controllers"

TILT = 40.0  # preview_linear_vel.py's tilt_angle
TP = 0.125  # preview_linear_vel.py's FREE_FALL_TIME
MU = 0.75
DT = 2e-4
setup()
NUM = {}


def load_profile_module():
    spec = importlib.util.spec_from_file_location("linear_vel_test", CTRL / "scripts" / "linear_vel_test.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


LVT = load_profile_module()


def profile_arrays(params=None, t_end=0.8):
    prof = LVT.Profile(params or {})
    t = np.arange(0.0, t_end, DT)
    v = np.array([prof.velocity(x) for x in t])
    return prof, t, v


# --------------------------------------------------------------------------- #
# 0. The preview itself, generated by the script                              #
# --------------------------------------------------------------------------- #
def fig_preview():
    out = FIGS / "preview_linear_vel.png"
    subprocess.run([sys.executable, str(CTRL / "scripts" / "preview_linear_vel.py"), "--no-show", "--out", str(out)],
                   check=True, capture_output=True)
    print("wrote", out)


# --------------------------------------------------------------------------- #
# 1. The preview's profile seen from the hand                                 #
# --------------------------------------------------------------------------- #
def fig_relative_view():
    prof, t, v = profile_arrays()
    tr = prof.pulse_time()
    g_a, g_n = g_components(TILT)
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(TEXTWIDTH, 2.5))
    sel = (t >= tr - 0.04) & (t <= tr + TP + 0.03)
    ms = (t - tr) * 1e3
    a1.axvspan(0, TP * 1e3, color=SHADE, lw=0)
    a1.plot(ms[sel], v[sel], color=INK, lw=1.8, label="hand (commanded profile)")
    tt = np.linspace(0, TP, 200)
    v0 = prof.velocity(tr)
    a1.plot(tt * 1e3, v0 - g_a * tt, color=C[0], ls="--", lw=1.6, label=r"bar, free fall $g\cos\theta$")
    cases = [(0.0, C[0], "--"), (0.5, C[2], "-"), (0.75, C[1], "-"), (1.0, C[6], "-")]
    for mu, col, ls in cases[1:]:
        tw, w, d = simulate_slip(t, v, tr, tr + TP, TILT, mu=mu)
        vh = np.interp(tw, t, v)
        a1.plot((tw - tr) * 1e3, vh + w, color=col, lw=1.6, label=rf"bar, $\mu={mu:g}$")
    a1.legend(loc="lower left", fontsize=6.6, ncol=2)
    a1.set_ylim(-1.0, 0.55)
    a1.set_xlabel("time from release [ms]")
    a1.set_ylabel("velocity along the axis [m/s]")
    a1.set_title("(a) velocities during the pulse")
    a1.axhline(0, color=INK2, lw=0.6)

    for mu, col, ls in cases:
        tw, w, d = simulate_slip(t, v, tr, tr + TP, TILT, mu=mu)
        a2.plot((tw - tr) * 1e3, d * 1e3, color=col, ls=ls, lw=1.8,
                label=(r"$\mu=0$ (preview: free, $g\cos\theta$)" if mu == 0 else rf"$\mu={mu}$ on lower finger"))
        NUM[f"relview_mu{int(mu*100)}_final"] = d[-1] * 1e3
        NUM[f"relview_mu{int(mu*100)}_max"] = d.max() * 1e3
        NUM[f"relview_mu{int(mu*100)}_wend"] = w[-1]
        NUM[f"relview_mu{int(mu*100)}_tapex"] = (tw[np.argmax(d)] - tr) * 1e3
    a2.axvspan(0, TP * 1e3, color=SHADE, lw=0, zorder=0)
    a2.set_xlabel("time from release [ms]")
    a2.set_ylabel(r"slip $\Delta$ (bar up the hand) [mm]")
    a2.set_title(r"(b) slip, $\theta=40^\circ$, $T_p=125$ ms")
    a2.legend(loc="upper left")
    a2.axhline(0, color=INK2, lw=0.6)
    fig.tight_layout()
    save(fig, FIGS / "relative_view.pdf")


# --------------------------------------------------------------------------- #
# 2. Matched velocity and matched pulse vs tilt                               #
# --------------------------------------------------------------------------- #
def fig_matched():
    th = np.linspace(0, 45, 181)
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(TEXTWIDTH, 2.5))
    for i, mu in enumerate([0.0, 0.5, 0.75, 1.0]):
        g_a, g_n = g_components(th)
        gp = g_a + mu * g_n
        col = [C[0], C[2], C[1], C[6]][i]
        a1.plot(th, v_star(TP, gp), color=col, ls="--" if mu == 0 else "-")
        label_end(a1, 45, v_star(TP, gp[-1]), rf"$\mu={mu:g}$")
        a2.plot(th, 2 * 0.45 / gp * 1e3, color=col, ls="--" if mu == 0 else "-")
        label_end(a2, 45, 2 * 0.45 / gp[-1] * 1e3, rf"$\mu={mu:g}$")
    for ax in (a1, a2):
        ax.set_xlabel(r"tilt $\theta$ [deg]")
        ax.set_xlim(0, 52)
        ax.axvline(TILT, color=MUTED, lw=0.8, ls=":")
    a1.axhline(0.45, color=INK, lw=1.0)
    a1.text(1, 0.455, "current 0.45 m/s", fontsize=7.5, color=INK, va="bottom")
    a1.set_ylabel(r"matched peak speed $v^*$ [m/s]")
    a1.set_title(r"(a) $v^* = \frac{1}{2} g_+ T_p$ for $T_p=125$ ms")
    a2.axhline(TP * 1e3, color=INK, lw=1.0)
    a2.text(1, TP * 1e3 + 2, "pulse 125 ms", fontsize=7.5, color=INK, va="bottom")
    a2.set_ylabel(r"matched pulse $T^* = 2v/g_+$ [ms]")
    a2.set_title(r"(b) $T^*$ for $v=0.45$ m/s")
    fig.tight_layout()
    save(fig, FIGS / "matched.pdf")
    g_a, g_n = g_components(TILT)
    for mu in (0.0, 0.5, 0.75, 1.0):
        NUM[f"vstar_mu{int(mu*100)}"] = v_star(TP, g_a + mu * g_n)
        NUM[f"tstar_mu{int(mu*100)}"] = 2 * 0.45 / (g_a + mu * g_n) * 1e3


# --------------------------------------------------------------------------- #
# 3. Genesis: slip vs pulse length for several peak speeds                    #
# --------------------------------------------------------------------------- #
def sweep_slip(path):
    d = np.load(path)
    v, L, o = d["vpeak"], d["length"], d["offset"]
    out = {}
    for tilt in d["tilts"]:
        k = f"t{int(tilt)}"
        rel, trig = d[k + "_rel_z"], d[k + "_trigger"]
        idx = np.arange(len(v))
        before = rel[idx, trig - 1]
        after = rel[idx, np.minimum(trig + L + 3, rel.shape[1] - 1)]
        out[int(tilt)] = (after - before) * 1e3
    return v, L, o, out


def fig_genesis_velocity():
    v, L, o, slip = sweep_slip(DATA / "pulse_slip_fast.npz")
    vs = np.unique(v)
    fig, axes = plt.subplots(1, 3, figsize=(TEXTWIDTH, 2.4), sharey=True)
    for ax, tilt in zip(axes, [0, 40, 45]):
        for j, vp in enumerate(vs):
            m = (v == vp) & (o == 0)
            Ls = L[m]
            order = np.argsort(Ls)
            x = (Ls[order] - 1) * 20
            y = slip[tilt][m][order]
            col = BLUE[j + 1] if len(vs) < len(BLUE) else BLUE[j]
            lw = 2.4 if abs(vp - 0.45) < 1e-6 else 1.5
            ax.plot(x, y, color=col, lw=lw, marker="o", ms=3.2)
            if ax is axes[-1]:
                label_end(ax, x[-1], y[-1], f"{vp:.2f} m/s")
        ax.axhline(0, color=INK2, lw=0.6)
        ax.axvline(120, color=MUTED, lw=0.8, ls=":")
        ax.set_title(rf"$\theta={tilt}^\circ$")
        ax.set_xlabel("forced-open window [ms]")
        ax.set_xticks([60, 80, 100, 120, 140, 160])
    axes[0].set_ylabel("slip per pulse [mm]")
    axes[-1].set_xlim(50, 200)
    fig.tight_layout()
    save(fig, FIGS / "genesis_velocity_sweep.pdf")
    # numbers for the text
    for tilt in (0, 40, 45):
        for vp in vs:
            for Lx in (6, 7, 8, 9):
                m = (v == vp) & (L == Lx) & (o == 0)
                NUM[f"gen_t{tilt}_v{int(round(vp*100))}_L{Lx}"] = float(slip[tilt][m][0])
            for off in (-1, 1):
                m = (v == vp) & (L == 7) & (o == off)
                NUM[f"gen_t{tilt}_v{int(round(vp*100))}_L7_off{'m' if off < 0 else 'p'}1"] = float(slip[tilt][m][0])


# --------------------------------------------------------------------------- #
# 4. Model vs Genesis at 1 kHz                                                #
# --------------------------------------------------------------------------- #
def equivalent_release(t, hv, ov, F, r0, g_a):
    j = r0
    while j < r0 + 80 and not np.all(F[j:j + 5] < 1e-3):
        j += 1
    line = ov[j] - g_a * (t - t[j])
    win = np.arange(r0 - 5, j + 1)
    return win[np.argmin(np.abs(line[win] - hv[win]))]


def regrip_index(F, r0):
    j = r0 + 100
    while F[j] < 1.0:
        j += 1
    return j


def fig_validation():
    d = np.load(DATA / "pulse_hires.npz")
    fr = d["frictions"]
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(TEXTWIDTH, 2.6))
    # (a) tilt 0: slip vs equivalent release instant
    k = "t0"
    rel, hv, ov = d[k + "_rel_z"], d[k + "_hand_v"], d[k + "_obj_v"]
    F = (d[k + "_f_l"] + d[k + "_f_r"]) / 2
    r0 = int(d[k + "_rev_substep"])
    t = np.arange(rel.shape[1]) * 1e-3
    ref = list(fr).index(0.75)
    grip = regrip_index(F[ref], r0)
    offs = np.arange(-30, 46, 1) * 1e-3
    model = [simulate_slip(t, hv[ref], t[r0] + x, t[grip], 0.0)[2][-1] * 1e3 for x in offs]
    a1.plot(offs * 1e3, model, color=C[0], lw=1.8, label="model (Genesis hand velocity)")
    pts = []
    for i, mu in enumerate(fr):
        if mu < 0.2:
            continue  # grip cannot hold the bar at all: not a release experiment
        kk = equivalent_release(t, hv[i], ov[i], F[i], r0, 9.81)
        meas = (rel[i, r0 + 200] - rel[i, r0 - 5]) * 1e3
        pts.append(((t[kk] - t[r0]) * 1e3, meas, mu))
    px = [p[0] for p in pts]
    py = [p[1] for p in pts]
    a1.plot(px, py, "o", color=C[1], ms=6, mec="white", mew=1.2, label="Genesis, 1 kHz")
    for x, y, mu in pts:
        a1.annotate(rf"$\mu={mu:g}$", (x, y), xytext=(5, -9), textcoords="offset points", fontsize=7, color=INK2)
        NUM[f"val0_mu{int(mu*100)}_rel"] = x
        NUM[f"val0_mu{int(mu*100)}_meas"] = y
    NUM["val0_model_peak"] = max(model)
    NUM["val0_model_peak_at"] = offs[int(np.argmax(model))] * 1e3
    pk = int(np.argmax(hv[ref][r0:r0 + 60]))
    a1.axvline(pk, color=MUTED, lw=0.8, ls=":")
    a1.text(pk - 1, -35, "hand velocity\npeak", fontsize=7, color=INK2, ha="right")
    a1.axhline(0, color=INK2, lw=0.6)
    a1.set_xlabel("effective release after commanded reversal [ms]")
    a1.set_ylabel("slip per pulse [mm]")
    a1.set_title(r"(a) $\theta=0^\circ$: slip is set by release timing")
    a1.legend(loc="lower right")

    # (b) tilts 40/45: slip vs contact friction
    rel_ms = {p[2]: p[0] for p in pts}
    for tilt, col in ((40, C[0]), (45, C[1])):
        k = f"t{tilt}"
        rel, hv = d[k + "_rel_z"], d[k + "_hand_v"]
        F = (d[k + "_f_l"] + d[k + "_f_r"]) / 2
        mus, meas, mod, free = [], [], [], []
        for i, mu in enumerate(fr):
            if mu not in rel_ms:
                continue
            grip = regrip_index(F[i], r0)
            tr = t[r0] + rel_ms[mu] * 1e-3
            mus.append(mu)
            meas.append((rel[i, r0 + 200] - rel[i, r0 - 5]) * 1e3)
            mod.append(simulate_slip(t, hv[i], tr, t[grip], tilt, mu=mu)[2][-1] * 1e3)
            free.append(simulate_slip(t, hv[i], tr, t[grip], tilt, mu=0.0)[2][-1] * 1e3)
            NUM[f"val{tilt}_mu{int(mu*100)}_meas"] = meas[-1]
            NUM[f"val{tilt}_mu{int(mu*100)}_model"] = mod[-1]
            NUM[f"val{tilt}_mu{int(mu*100)}_free"] = free[-1]
        a2.plot(mus, mod, color=col, lw=1.8)
        a2.plot(mus, free, color=col, lw=1.2, ls="--")
        a2.plot(mus, meas, "o", color=col, ms=6, mec="white", mew=1.2)
        label_end(a2, mus[-1], mod[-1], rf"{tilt}$^\circ$ Coulomb", dy=(5 if tilt == 45 else -5))
        label_end(a2, mus[-1], free[-1], rf"{tilt}$^\circ$ free fall", dy=0)
    a2.plot([], [], "o", color=INK2, label="Genesis, 1 kHz")
    a2.plot([], [], color=INK2, lw=1.8, label=r"model, $g_\pm=g(\cos\theta\pm\mu\sin\theta)$")
    a2.plot([], [], color=INK2, lw=1.2, ls="--", label=r"model, $g\cos\theta$ only")
    a2.set_xlim(0.2, 1.3)
    a2.set_xlabel(r"contact friction $\mu$")
    a2.set_ylabel("slip per pulse [mm]")
    a2.set_title("(b) tilted: the bar slides on the lower finger")
    a2.legend(loc="upper left", fontsize=6.8)
    fig.tight_layout()
    save(fig, FIGS / "validation.pdf")


# --------------------------------------------------------------------------- #
# 5. What the arm actually does: the reference chain and the timing budget    #
# --------------------------------------------------------------------------- #
def fig_chain():
    prof, t, v = profile_arrays(t_end=0.45)
    ch = controller_chain(t, v)
    arm = ch["arm"]
    trev = prof.reverse_start
    send = prof.pulse_send_time()
    tpk = t[np.argmax(arm)]
    NUM["chain_arm_peak"] = arm.max()
    NUM["chain_arm_min"] = arm.min()
    NUM["chain_pub_peak"] = ch["published"].max()
    NUM["chain_delay_peak"] = (tpk - trev) * 1e3
    acc = np.gradient(arm, t[1] - t[0])
    NUM["chain_arm_decel"] = -acc.min()
    fig, a1 = plt.subplots(1, 1, figsize=(TEXTWIDTH, 2.6))
    a1.plot(t * 1e3, v, color=MUTED, lw=1.2, label="profile (Profile.velocity)")
    a1.step(t * 1e3, ch["published"], where="post", color=INK2, lw=1.0, label="published at 50 Hz")
    a1.plot(t * 1e3, ch["reference"], color=C[0], lw=1.4, ls="--", label="controller reference (cubic, one period late)")
    a1.plot(t * 1e3, ch["lowpass"], color=C[2], lw=1.4, label="after low-pass + max_accel")
    a1.plot(t * 1e3, arm, color=C[1], lw=2.0, label="hand (arm model)")
    a1.axvline(send * 1e3, color=C[7], lw=1.2)
    a1.axvline(trev * 1e3, color=INK, lw=0.8, ls=":")
    a1.axvline(tpk * 1e3, color=C[1], lw=0.8, ls=":")
    ytop = 0.52
    a1.annotate("", xy=(tpk * 1e3, ytop), xytext=(send * 1e3, ytop),
                arrowprops=dict(arrowstyle="<->", color=INK2, lw=0.8))
    a1.text((send + tpk) / 2 * 1e3, ytop + 0.02, f"{(tpk - send) * 1e3:.0f} ms", ha="center", fontsize=7.5, color=INK)
    a1.text(send * 1e3 - 2, -0.58, "pulse\nrequest", ha="right", fontsize=7, color=INK2)
    a1.text(trev * 1e3 - 1, -0.40, "commanded\nreversal", ha="right", fontsize=7, color=INK2)
    a1.text(tpk * 1e3 + 2, -0.58, "actual\nreversal", ha="left", fontsize=7, color=INK2)
    a1.set_xlim(0, 360)
    a1.set_ylim(-0.65, 0.62)
    a1.set_xlabel("time [ms]")
    a1.set_ylabel("velocity along the axis [m/s]")
    a1.legend(loc="upper right", fontsize=6.8)
    fig.tight_layout()
    save(fig, FIGS / "chain.pdf")


def aligned_params(v, A=15.0, T_rev_hold=None):
    """linear_vel_test settings with the reversal on a publish tick and a matching reverse hold."""
    t_up = 0.02 * np.ceil(v / 4.0 / 0.02)
    params = {"target_vel": v, "accel_up": v / t_up, "accel_down": A}
    if T_rev_hold is not None:
        params["reverse_hold"] = T_rev_hold
    return params


def slip_vs_latency(params, tilt, mu, lat_ms, Tp=TP):
    prof, t, v = profile_arrays(params, t_end=1.2)
    arm = controller_chain(t, v)["arm"]
    out = []
    for L in lat_ms:
        tr = prof.pulse_send_time() + L * 1e-3
        _, w, d = simulate_slip(t, arm, tr, tr + Tp, tilt, mu=mu)
        out.append((d[-1] * 1e3, w[-1], d.max() * 1e3))
    return np.array(out), prof, t, arm


def fig_latency():
    lat = np.arange(0, 81, 2.0)
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(TEXTWIDTH, 2.6), sharey=True)
    configs = [
        ("current: 0.45 m/s (defaults)", {}, C[0]),
        ("0.65 m/s, reversal on a tick", aligned_params(0.65, T_rev_hold=0.15), C[1]),
    ]
    for ax, mu, title in ((a1, 0.0, r"(a) free bar, $g\cos\theta$ (preview)"),
                          (a2, MU, rf"(b) bar on lower finger, $\mu={MU}$")):
        for name, params, col in configs:
            res, prof, _, _ = slip_vs_latency(params, TILT, mu, lat)
            band = [slip_vs_latency(params, TILT, m, lat)[0][:, 0] for m in (0.6, 0.9)] if mu > 0 else None
            if band is not None:
                ax.fill_between(lat, np.minimum(*band), np.maximum(*band), color=col, alpha=0.15, lw=0)
            ax.plot(lat, res[:, 0], color=col, lw=1.8, label=name)
            best = int(np.argmax(res[:, 0]))
            ax.plot(lat[best], res[best, 0], "o", color=col, ms=5, mec="white", mew=1)
            key = "cur" if not params else "fast"
            NUM[f"lat_{key}_mu{int(mu*100)}_best"] = res[best, 0]
            NUM[f"lat_{key}_mu{int(mu*100)}_bestlat"] = lat[best]
            i10 = [np.argmin(np.abs(lat - (lat[best] + s))) for s in (-10, 10)]
            NUM[f"lat_{key}_mu{int(mu*100)}_pm10"] = (res[i10[0], 0], res[i10[1], 0])
            NUM[f"lat_{key}_mu{int(mu*100)}_wbest"] = res[best, 1]
        ax.axhline(0, color=INK2, lw=0.6)
        ax.set_xlabel("Robotiq latency, request to release [ms]")
        ax.set_title(title)
    a1.set_ylabel(r"slip per pulse, $T_p=125$ ms [mm]")
    a1.legend(loc="upper left", fontsize=6.8)
    a2.text(2, -12, r"band: $\mu\in[0.6,0.9]$", fontsize=7, color=INK2)
    fig.tight_layout()
    save(fig, FIGS / "latency.pdf")


def fig_design_map():
    """Slip at re-grip and slip lost after the apex over (peak speed, pulse length)."""
    vs = np.linspace(0.25, 0.85, 25)
    tps = np.linspace(0.06, 0.20, 29)
    D = np.zeros((len(tps), len(vs)))
    lost = np.zeros_like(D)
    W = np.zeros_like(D)
    for j, v in enumerate(vs):
        prof, t, vp = profile_arrays(aligned_params(v, T_rev_hold=0.2), t_end=1.4)
        arm = controller_chain(t, vp)["arm"]
        tr = t[np.argmax(arm)]  # release on the actual reversal
        for i, T in enumerate(tps):
            _, w, d = simulate_slip(t, arm, tr, tr + T, TILT, mu=MU)
            D[i, j] = d[-1] * 1e3
            lost[i, j] = (d.max() - d[-1]) * 1e3
            W[i, j] = w[-1]
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(TEXTWIDTH, 2.8), sharey=True)
    lim = np.nanmax(np.abs(D))
    cs = a1.contourf(vs, tps * 1e3, D, levels=np.linspace(-lim, lim, 25), cmap=DIVERGING)
    cl = a1.contour(vs, tps * 1e3, D, levels=[0, 5, 10, 15, 20, 25, 30], colors=INK2, linewidths=0.6)
    a1.clabel(cl, fmt="%d mm", fontsize=6.5)
    fig.colorbar(cs, ax=a1, label="slip at re-grip [mm]", ticks=[-30, -15, 0, 15, 30])
    top = 5.0 * np.ceil(lost.max() / 5.0)
    cs2 = a2.contourf(vs, tps * 1e3, lost, levels=np.arange(0, top + 0.1, 2.5), cmap="Blues")
    fig.colorbar(cs2, ax=a2, label="slip lost after apex [mm]", ticks=np.arange(0, top + 0.1, 10))
    for ax in (a1, a2):
        ax.contour(vs, tps * 1e3, W, levels=[0.0], colors=INK, linewidths=1.6)
        ax.plot(0.45, TP * 1e3, "o", color="white", mec=INK, ms=7, mew=1.5)
        ax.annotate("current", (0.45, TP * 1e3), xytext=(6, 6), textcoords="offset points", fontsize=7.5, color=INK)
        ax.set_xlabel("commanded peak speed $v$ [m/s]")
        ax.grid(False)
    a1.set_ylabel("pulse length $T_p$ [ms]")
    a1.set_title(r"(a) slip, black line: $w=0$ at re-grip")
    a2.set_title("(b) cost of a pulse that outlasts the apex")
    fig.tight_layout()
    save(fig, FIGS / "design_map.pdf")
    j45 = int(np.argmin(np.abs(vs - 0.45)))
    NUM["map_T_apex_045"] = tps[int(np.argmax(D[:, j45]))] * 1e3
    NUM["map_Dmax_045"] = D[:, j45].max()
    i125 = int(np.argmin(np.abs(tps - TP)))
    jz = int(np.argmin(np.abs(W[i125])))
    NUM["map_vmatch_125"] = vs[jz]
    NUM["map_D_vmatch_125"] = D[i125, jz]


SWEEP_TILTS = [0, 10, 20, 30, 40, 45]


def fig_tilt_velocity():
    """Slip at re-grip against peak speed, one curve per tilt, for the current pulse."""
    vs = np.arange(0.20, 0.8501, 0.025)
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(TEXTWIDTH, 2.9), sharey=True)
    arms = []
    for v in vs:
        prof, t, vp = profile_arrays(aligned_params(v, T_rev_hold=0.2), t_end=1.4)
        arm = controller_chain(t, vp)["arm"]
        arms.append((t, arm, t[np.argmax(arm)]))  # release on the hand's actual reversal
    for i, tilt in enumerate(SWEEP_TILTS):
        col = BLUE[i]
        D, W = [], []
        for t, arm, tr in arms:
            _, w, d = simulate_slip(t, arm, tr, tr + TP, tilt, mu=MU)
            D.append(d[-1] * 1e3)
            W.append(w[-1])
        D, W = np.array(D), np.array(W)
        a1.plot(vs, D, color=col, label=rf"$\theta={tilt}^\circ$")
        NUM[f"tiltsweep_model_t{tilt}_v045"] = float(np.interp(0.45, vs, D))
        k = np.where(np.diff(np.sign(W)) > 0)[0]  # w crosses zero from below: matched
        if len(k):
            j = k[0]
            vm = vs[j] - W[j] * (vs[j + 1] - vs[j]) / (W[j + 1] - W[j])
            dm = float(np.interp(vm, vs, D))
            a1.plot(vm, dm, "o", color=col, ms=6, mec="white", mew=1.2, zorder=5)
            NUM[f"tiltsweep_model_t{tilt}_vmatch"] = float(vm)
            NUM[f"tiltsweep_model_t{tilt}_dmatch"] = dm

    d = np.load(DATA / "pulse_slip_tilts.npz")
    v, L = d["vpeak"], d["length"]
    order = np.argsort(v)
    for i, tilt in enumerate(SWEEP_TILTS):
        k = f"t{tilt}"
        rel, trig, ee = d[k + "_rel_z"], d[k + "_trigger"], d[k + "_ee_z"]
        idx = np.arange(len(v))
        slip = (rel[idx, np.minimum(trig + L + 3, rel.shape[1] - 1)] - rel[idx, trig - 1]) * 1e3
        reset = (np.abs(np.diff(ee, axis=1)) > 0.03).any(axis=1)
        slip = np.where(reset, np.nan, slip)
        a2.plot(v[order], slip[order], color=BLUE[i], marker="o", ms=3, label=rf"$\theta={tilt}^\circ$")
        NUM[f"tiltsweep_gen_t{tilt}_v045"] = float(slip[np.argmin(np.abs(v - 0.45))])
        NUM[f"tiltsweep_gen_t{tilt}_max"] = float(np.nanmax(slip))
        NUM[f"tiltsweep_gen_t{tilt}_vmax"] = float(v[np.nanargmax(slip)])
        NUM[f"tiltsweep_gen_t{tilt}_resets"] = int(reset.sum())

    for ax in (a1, a2):
        ax.axvline(0.45, color=INK, lw=1.0, ls=":")
        ax.axhline(0, color=INK2, lw=0.6)
        ax.set_xlabel("commanded peak speed $v$ [m/s]")
    a1.text(0.455, a1.get_ylim()[1] * 0.97, "current\n0.45 m/s", fontsize=7, color=INK2, va="top")
    a1.set_ylabel("relative $Z$ displacement per pulse [mm]")
    a1.set_title(r"(a) model, $T_p=125$ ms, $\mu=0.75$")
    a2.set_title("(b) Genesis, 120 ms forced open")
    a1.legend(loc="lower right", fontsize=6.8, ncol=2)
    fig.tight_layout()
    save(fig, FIGS / "tilt_velocity_sweep.pdf")


FRICTION_GRID = np.round(np.arange(0.0, 1.0001, 0.05), 2)
FRICTION_TABLE = [0.0, 0.3, 0.5, 0.75, 1.0]


def matched_through_chain(arms, vs, tilt, mu):
    """Peak speed where w crosses zero at re-grip, and the slip there, through the full chain."""
    W, D = [], []
    for t, arm, tr in arms:
        _, w, d = simulate_slip(t, arm, tr, tr + TP, tilt, mu=mu)
        W.append(w[-1])
        D.append(d[-1] * 1e3)
    W, D = np.array(W), np.array(D)
    k = np.where(np.diff(np.sign(W)) > 0)[0]
    if not len(k):
        return np.nan, np.nan
    j = k[0]
    vm = vs[j] - W[j] * (vs[j + 1] - vs[j]) / (W[j + 1] - W[j])
    return float(vm), float(np.interp(vm, vs, D))


def fig_friction_sweep():
    """Matched speed v* and the slip it gives, against contact friction, one curve per tilt."""
    vs = np.arange(0.30, 1.1001, 0.01)
    arms = []
    for v in vs:
        prof, t, vp = profile_arrays(aligned_params(v, T_rev_hold=0.2), t_end=1.6)
        arm = controller_chain(t, vp)["arm"]
        arms.append((t, arm, t[np.argmax(arm)]))
    grid = sorted(set(FRICTION_GRID) | set(FRICTION_TABLE))
    res = {}
    for tilt in SWEEP_TILTS:
        for mu in grid:
            res[(tilt, mu)] = matched_through_chain(arms, vs, tilt, mu)

    fig, (a1, a2) = plt.subplots(1, 2, figsize=(TEXTWIDTH, 2.8))
    for i, tilt in enumerate(SWEEP_TILTS):
        vm = np.array([res[(tilt, mu)][0] for mu in grid])
        dm = np.array([res[(tilt, mu)][1] for mu in grid])
        a1.plot(grid, vm, color=BLUE[i], label=rf"$\theta={tilt}^\circ$")
        a2.plot(grid, dm, color=BLUE[i], label=rf"$\theta={tilt}^\circ$")
    a1.axhline(0.45, color=INK, lw=1.0, ls=":")
    a1.text(0.99, 0.455, "current 0.45 m/s", fontsize=7, color=INK2, va="bottom", ha="right")
    for mu in (0.3, 0.75):
        for ax in (a1, a2):
            ax.axvline(mu, color=MUTED, lw=0.7, ls="--")
            ax.text(mu + 0.01, 1.0, rf"$\mu={mu:g}$", transform=ax.get_xaxis_transform(), fontsize=6.8,
                    color=INK2, va="top")
    for ax in (a1, a2):
        ax.set_xlabel(r"contact friction $\mu$ (bar on lower finger)")
        ax.set_xlim(0, 1.0)
    a1.set_ylabel(r"matched peak speed $v^*$ [m/s]")
    a1.set_title(r"(a) $v^*$ for $T_p=125$ ms, full chain")
    a2.set_ylabel(r"slip at $v^*$ [mm]")
    a2.set_title(r"(b) relative $Z$ displacement at $v^*$")
    a1.legend(loc="upper left", bbox_to_anchor=(0.0, 0.93), fontsize=6.8, ncol=2)
    fig.tight_layout()
    save(fig, FIGS / "friction_sweep.pdf")

    # table: closed form / full chain, rows = tilts, columns = friction values
    lines = []
    for tilt in SWEEP_TILTS:
        g_a, g_n = g_components(tilt)
        cells = []
        for mu in FRICTION_TABLE:
            vc = v_star(TP, g_a + mu * g_n)
            vm, dm = res[(tilt, mu)]
            cells.append(f"{vc:.2f}\\,/\\,{vm:.2f}")
            NUM[f"fric_t{tilt}_mu{int(round(mu * 100))}_closed"] = vc
            NUM[f"fric_t{tilt}_mu{int(round(mu * 100))}_chain"] = vm
            NUM[f"fric_t{tilt}_mu{int(round(mu * 100))}_slip"] = dm
        lines.append(f"${tilt}^\\circ$ & " + " & ".join(cells) + " \\\\")
    (HERE / "friction_table.tex").write_text("\n".join(lines) + "\n")
    print("wrote friction_table.tex")


def design_table():
    rows = []
    cases = [
        ("current defaults", {}, TP),
        ("reversal on a tick", aligned_params(0.45, T_rev_hold=0.1), TP),
        ("matched speed", aligned_params(0.65, T_rev_hold=0.15), TP),
        ("matched pulse", aligned_params(0.45, T_rev_hold=0.1), 0.085),
    ]
    lat = np.arange(0, 81, 1.0)
    for name, params, Tp in cases:
        res, prof, t, arm = slip_vs_latency(params, TILT, MU, lat, Tp=Tp)
        best = int(np.argmax(res[:, 0]))
        lo, hi = np.clip(best - 10, 0, len(lat) - 1), np.clip(best + 10, 0, len(lat) - 1)
        mus = [slip_vs_latency(params, TILT, m, lat[[best]], Tp=Tp)[0][0, 0] for m in (0.6, 0.9)]
        free_res = slip_vs_latency(params, TILT, 0.0, lat, Tp=Tp)[0]
        free = free_res[:, 0].max()
        high, low = prof.extremes()
        acc = np.gradient(arm, t[1] - t[0])
        rows.append({
            "name": name, "v": prof.target, "a_up": prof.accel_up, "Tp": Tp * 1e3,
            "lat": lat[best], "slip": res[best, 0], "w": res[best, 1],
            "pm10": (res[lo, 0], res[hi, 0]), "mu": tuple(mus), "free": free,
            "arm_peak": arm.max(), "arm_min": arm.min(), "arm_acc": np.abs(acc).max(),
            "high": high * 1e3, "low": low * 1e3,
        })
    (HERE / "design_table.json").write_text(json.dumps(rows, indent=1, default=float))
    lines = []
    for r in rows:
        lines.append(
            f"{r['name']} & {r['v']:.2f} & {r['Tp']:.0f} & {r['lat']:.0f} & {r['slip']:.1f} & "
            f"{r['pm10'][0]:.1f}\\,/\\,{r['pm10'][1]:.1f} & {min(r['mu']):.1f}--{max(r['mu']):.1f} & "
            f"{r['w']:+.2f} & {r['free']:.1f} & {r['arm_peak']:.2f}\\,/\\,{r['arm_min']:.2f} & "
            f"{r['high']:+.0f}\\,/\\,{r['low']:+.0f} \\\\"
        )
    (HERE / "design_table.tex").write_text("\n".join(lines) + "\n")
    print("wrote design_table.tex")


def write_numbers():
    g_a, g_n = g_components(TILT)
    NUM.update({
        "ga": g_a, "gn": g_n, "gplus": g_a + MU * g_n, "gminus": g_a - MU * g_n,
        "closed_D": slip_closed(0.9, 15.0, TP, g_a) * 1e3, "closed_w": float(w_end(0.9, 15.0, TP, g_a)),
        "closed_Dstar": slip_star(TP, 15.0, g_a) * 1e3,
    })
    s_before, s_after = timing_sensitivity(0.9, 15.0, TP, g_a, 4.0)
    NUM["sens_before"], NUM["sens_after"] = s_before, s_after
    lines = []
    for k, v in NUM.items():
        name = "N" + "".join(ch for ch in k.title() if ch.isalpha())
        if isinstance(v, tuple):
            v = f"{v[0]:.1f}/{v[1]:.1f}"
            lines.append(f"% {k}\n\\newcommand{{\\{name}}}{{{v}}}")
        else:
            lines.append(f"% {k}\n\\newcommand{{\\{name}}}{{{v:.3g}}}")
    (HERE / "numbers.tex").write_text("\n".join(lines) + "\n")
    (HERE / "numbers.json").write_text(json.dumps(NUM, indent=1, default=float))
    print("wrote numbers.tex")


if __name__ == "__main__":
    fig_preview()
    fig_relative_view()
    fig_matched()
    fig_genesis_velocity()
    fig_validation()
    fig_chain()
    fig_latency()
    fig_design_map()
    fig_tilt_velocity()
    fig_friction_sweep()
    design_table()
    write_numbers()
